[package]
name = "gm-bin"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "gm"
path = "src/main.rs"

[features]
default = []
demo = ["gm-tui/demo"]

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
gm-tui = { path = "../tui" }
tokio = { workspace = true }
walletconnect-sdk = { workspace = true }
console = { workspace = true }