[package]
name = "gm-bin"
version = "0.0.2-alpha"
edition = "2021"

[[bin]]
name = "gm"
path = "src/main.rs"

[features]
default = []
demo = ["gm-tui/demo"]

[dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
gm-tui = { path = "../tui" }
gm-ratatui-extra = { path = "../ratatui-extra" }
gm-utils = { path = "../utils" }
tokio = { workspace = true }
walletconnect-sdk = { workspace = true }
console = { workspace = true }
ratatui = { workspace = true }